### ISSUE TITLE
プレイヤーマッチングにおいて、getNameByIdができないエラー

### ISSUE THREAD

**Issue by yunkai1841** [sh-tak/PokemonishGame#25]
`main`ブランチのみで起きる

https://github.com/sh-tak/PokemonishGame/blob/a673e0ad5850c10ced143ad02acb4c3a51df934d/server/Server.java#L164

```bash
Exception in thread "Thread-2" java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 128
        at server.Server.getNameById(Server.java:165)
        at server.Channel.run(Channel.java:86)
```

**Comment by sh-tak** [comment]
多分マージした時にコンフリクト起きててごちゃごちゃしてたら色々混ざって変な感じになったからだと思うからdefaultをfeature-guiにする。(一応old-mainとして今のmainも残しとく)
